#!/usr/bin/env sh
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd  $SCRIPT_DIR

if ./tests/iceoryx2-cxx-tests ; then
    echo "PASS: iceoryx2-cxx-tests"
else
    echo "FAIL: iceoryx2-cxx-tests"
fi
